test_save: false
num_workers: 4
dryrun: false
email: avmendoz@cs.unc.edu
save_on_crash: true
save_after_exp: true
email_on_failure: true
save_after_epoch: true
img_first: true
use_raw_imgs: false
batch_size: 4
