test_save: false
img_first: true
use_raw_imgs: true
arrow_fields: ''
batch_size: 4
num_workers: 4
dryrun: false
email: avmendoz@cs.unc.edu
save_on_crash: true
save_after_exp: true
email_on_failure: true
save_after_epoch: true
