test_save: false
save_after_exp: false
img_first: false
use_raw_imgs: false
batch_size: 4
num_workers: 4
dryrun: true
skip_eval: false
private_file: sample.py
skip_train: false
skip_eval: false
email: null
