aux_gpu: 3
ckp_name: /home/avmendoz/outputs/data_gqa
command: data
data:
  add_special_tokens: true
  arrow_fields: null
  attribute_file: ''
  drop_last: true
  eval_split: eval
  feature_mask_rate: 0.15
  ignore_id: -100
  img_first: false
  img_format: jpg
  img_max_size: 388
  max_objects: 36
  num_attrs: 400
  num_objects: 1600
  num_workers: 8
  object_file: ''
  patch_size: 16
  percent_data: 1.0
  pin_memory: true
  pos_dim: 4
  random_feature_rate: 0.1
  random_word_rate: 0.1
  return_attention_mask: true
  return_tensors: pt
  return_token_type_ids: true
  sent_length: 20
  sentence_match_rate: 0.5
  shuffle: true
  skip_eval: false
  split: train
  truncate_sentence: true
  use_raw_imgs: false
  valid_split: valid
  word_mask_rate: 0.15
datasets: gqa
dryrun: false
eval_aliases: !!python/tuple
- testdev
- eval
- dev
- evaluation
- inference
evaluate: null
experiment: {}
gpu: 0
known_commands: !!python/tuple
- train
- pretrain
- data
- eval
- null
logdir: /home/avmendoz/logs
logfile: /home/avmendoz/logs/logs.txt
logging: true
model:
  ckp_name_or_path: ''
  ckp_transformers: unc-nlp/lxmert-base-uncased
  from_transformers: true
  known_labels: 1842
  l_layers: 9
  load_epoch: 0
  r_layers: 5
  vit_variant: ViT-B_16
  x_layers: 5
model_name: null
output_dir: /home/avmendoz/outputs
pathes:
  coco_captions: /playpen1/home/avmendoz/data/coco_captions/
  coco_test_arrow: null
  coco_train_arrow: null
  coco_valid_arrow: null
  datadirs: /playpen1/home/avmendoz/data
  gqa_labels: /playpen1/home/avmendoz/data/temp_gqa/gqa_labels.json
  gqa_test: /playpen1/home/avmendoz/data/
  gqa_testdev: /playpen1/home/avmendoz/data/temp_gqa/testdev.json
  gqa_train: /playpen1/home/avmendoz/data/temp_gqa/train/
  gqa_val: /playpen1/home/avmendoz/data/temp_gqa/train/valid.json
  temp_lxmert_answers: /playpen1/home/avmendoz/data/labels/lxmert_answers.json
  temp_lxmert_eval: /playpen1/home/avmendoz/data/lxmert_data/mscoco_minival.json
  temp_lxmert_test: /playpen1/home/avmendoz/data/
  temp_lxmert_train: /playpen1/home/avmendoz/data/lxmert_data/train/
  vg_captions: /playpen1/home/avmendoz/data/vg_captions/
  vg_test: /playpen1/home/avmendoz/data/vg/test
  vg_test_arrow: /playpen1/home/avmendoz/data/arrow/vg_test.arrow
  vg_train: /playpen1/home/avmendoz/data/vg/train
  vg_train_arrow: /playpen1/home/avmendoz/data/arrow/vg_train.arrow
  vit_pretrained_dir: /playpen1/home/avmendoz/data/vit/
  vq_qa: /playpen1/home/avmendoz/data/vg_qa/
  vqa: /playpen1/home/avmendoz/data/vqa/
percent_min_gpu_free_mem: 0.75
print_config: true
private: {}
run:
  batch_size: 32
  half_precision: true
  task_mask_lm: false
  task_matched: false
  task_obj_predict: false
  visual_attr_loss: false
  visual_feat_loss: false
  visual_obj_loss: false
seed: 1
test_aliases: !!python/tuple
- test
train_aliases: !!python/tuple
- train
- finetune
- pretrain
valid_aliases: !!python/tuple
- val
- valid
- validation
